### ISSUE TITLE
[FE] refactor: 로그인 후 신청페이지로 넘어가면 '신청기간이 아닙니다.'라는 alert 창이 4번 나오는데 1번으로 변경

### ISSUE THREAD

**Issue by smb0123** [JNU-Parking-Ticket-Project/Parking-Ticket-FE#235]
## 리팩터링 내용
로그인 후 신청페이지로 넘어가면 '신청기간이 아닙니다.' 라는 alert 창이 4번 나오는데 1번으로 변경하겠습니다.
![image](https://github.com/user-attachments/assets/9704877e-d935-4d49-90d3-c7614db35916)

<br/>

## 체크리스트

- [ ] `assignee` 설정 (선택)
- [x] `labels` 설정

**Comment by loopy-lim** [comment]
이게 참 에러에 대해서 다루기가 엄청 어려운 것 같은데 심지어 error와 alert에 관한 연관성이 더 있어서 어려운 것 같아요.

그래서 globalThis에 alert 객체를 오버라이딩하는 것이 어떤지 추천해봅니다. 현재 생각나는 구현 방식은 다음과 같습니다.
alert를 받으면 alert내부에서 queue로서 그 alert string객체를 관리합니다.
alert를 넘길 때, error객체인지 검사하고, error객체라면 id를 받는 로직을 작성합니다.
그 id와 들어오는 순서에 따라서 중복인지 아닌지 검사하며, 보여주어야 하는 에러인지 검사하는 로직이 들어가면 더 자연스럽지 않을까 싶습니다.
특히 id에 따라 작동하는 방법을 다르게 할 수 있으므로 더 편리하지 않을까 싶습니다.

**Comment by 2yunseong** [comment]
@loopy-lim 음 .. alert 자체를 오버라이드 하는 건 위험한 생각같다는 느낌이..

**Comment by loopy-lim** [comment]
그러게요... 흠... 아니면 alert 대신에 toast를 하는 건 어떤가요??

**Comment by 2yunseong** [comment]
그것도 괜찮아 보입니다

**Comment by 2yunseong** [comment]
https://overlay-kit.slash.page/introduction.html
https://www.slash.page/ko/libraries/react/use-overlay/src/useOverlay.i18n

**Comment by loopy-lim** [comment]
역시 국내 원탑 토스?

**Comment by 2yunseong** [comment]
토스트 만들어서 띄우기가 쉬움
